Major update with Sub&Crab Keyboard mechanics implemented.
SeijiEmery/KelplerEffectPrototype pull request #2
Opened 2019-11-09 00:10 UTC by CCD729

Await for reviews .

2019-11-09 00:24 UTC, SeijiEmery requested changes
Needs some changes to BulletMotion.cs; after that can be merged.

Test scenes + scripts are fine until we get the other scripts needed for ship controls + movement up (which can / should be another feature branch + PR); we'll update / refactor this when those are done.

2019-11-09 00:24 UTC, SeijiEmery commented on Assets/TestScript/BulletMovement.cs
>          }
remove these lines. if collision occurs, move the projectile in front of the barrel, or remove the collider on the barrel, etc. Or add physics layers in your test scene: https://docs.unity3d.com/Manual/LayerBasedCollision.html. we'll have a better solution for this long term, but we don't want these lines in this script.

2019-11-09 00:24 UTC, SeijiEmery commented on Assets/TestScript/CrabTestController.cs
> +        if (Input.GetKey(KeyCode.Tab))
would ideally be using GetAxis + GetButton but this is fine

2019-11-09 00:24 UTC, SeijiEmery commented on Assets/TestScript/BulletMovement.cs
>          }
BulletMovement.cs should be merged w/ Scripts/Projectile/Projectile.cs and renamed to Scripts/Projectile/ProjectileMovement.cs

2019-11-09 00:24 UTC, SeijiEmery commented on Assets/TestScript/BulletMovement.cs
>          }
should add destruction timer:
`public bool destroySelfAfterTimeout = false`
`public float timeoutLifetime = 10f`

Track timeout using Start() and Time.time, eg. add a private variable private float `destructionTime`, init to `destructionTime = Time.time + timeoutLifetime`, and trigger destruction iff `destructionTime <= Time.time`

destroy on timeout iff `destroySelfAfterTimeout == true`.

if you find a better way to implement this do that

2019-11-09 00:24 UTC, SeijiEmery commented on Assets/TestScript/BulletMovement.cs
>          }
should add a public `Destroy()` method that can be called externally and move destruction there

2019-11-09 00:24 UTC, SeijiEmery commented on Assets/TestScript/BulletMovement.cs
>          }
should add a `public bool destroySelfOnFirstCollision = false` variable and use that to destroy this object on collision iff that is set to true

2019-11-09 00:26 UTC, SeijiEmery commented on Assets/TestScript/BulletMovement.cs
>          }
bunch of stuff, but if all of these are done I'll say that Scripts/Projectile/ProjectileMotion.cs is done.

2019-11-09 00:30 UTC, SeijiEmery requested changes
sub prefab needs to be renamed. everything else looks fine

2019-11-09 00:30 UTC, SeijiEmery commented on Assets/Prefabs/TempRedShip.prefab
> +  m_ObjectHideFlags: 0
rename this => Prefabs/Sub.prefab

2019-11-09 00:36 UTC, SeijiEmery commented on Assets/TestScript/CrabTestController.cs
> +        if (Input.GetKey(KeyCode.Tab))
actually, could you edit Edit > ProjectSettings > Input:

- rename Horizontal => MoveX and Vertical => MoveZ
- add MoveY axis + add bindings for shift (down) and tab (up). Should be setup the same as the Horizontal + Vertical axes
- add TurnHorizontal axis (Q + E)
- add TurnVertical axis (duplicate bindings to shift + tab)

then you can refactor to:

`var movement = Vector3.forward * Input.GetAxis("MoveZ") + Vector3.up * ...`
`transform.Translate(movement * speed * Time.deltaTime, Space.World)`

2019-11-09 00:38 UTC, SeijiEmery commented on Assets/TestScript/CrabTestController.cs
> +        if (Input.GetKey(KeyCode.Tab))
note: if you do this we should be able to use both WASD and arrow keys for movement :)

2019-11-09 00:41 UTC, SeijiEmery commented on Assets/TestScript/BulletMovement.cs
>          }
we'll still need damage, etc., but that can be a separate PR

2019-11-10 02:31 UTC, CCD729 commented on Assets/TestScript/BulletMovement.cs
>          }
Done. Please check bullet prefabs and ProjectileMovement.cs for details.

2019-11-10 10:12 UTC, CCD729 commented on Assets/Prefabs/TempRedShip.prefab
> +  m_ObjectHideFlags: 0
Renamed.

2019-11-10 11:20 UTC, CCD729 commented on Assets/TestScript/CrabTestController.cs
> +        if (Input.GetKey(KeyCode.Tab))
The new input system applied to all prefabs. MortarShells now got similar behaviors as projectiles. Optimized some code structure.

2019-11-10 11:20 UTC, CCD729 commented
Await for a second round of reviews.

2019-11-10 23:45 UTC, kodomazer requested changes
Just some minor naming changes.
I haven't opened it in the editor at all, so there might be other things that need to be changed.

Also, I tend to use:
```
[SerializedField]
private type name;
```
As my paradigm for getting variables to show up in the editor that would otherwise be private variables instead of simply making them `public`

2019-11-10 23:45 UTC, kodomazer commented on Assets/Script/Projectiles/ProjectileMovement.cs
> +        transform.Translate(Vector3.up * Time.deltaTime * speed);
Use `Time.fixedDeltaTime` in FixedUpdate

2019-11-10 23:45 UTC, kodomazer commented on Assets/Script/Projectiles/ProjectileMovement.cs
> +    public bool destroySelfOnFirstCollision = false;
This should be `destroySelfOnCollision` as its usage doesn't make it conditionally destroy itself on the second collision instead.

2019-11-10 23:45 UTC, kodomazer commented on Assets/TestScript/MortarMovement.cs
> +    public bool destroySelfOnFirstCollision = false;
Same as above, rename to `destroySelfOnCollision` because it just controls if a collision destroys this.

2019-11-11 00:15 UTC, SeijiEmery approved these changes
Looks good; just address kodo’s change requests?

2019-11-11 00:49 UTC, CCD729 commented on Assets/Script/Projectiles/ProjectileMovement.cs
> +        transform.Translate(Vector3.up * Time.deltaTime * speed);
Replaced.

2019-11-11 00:49 UTC, CCD729 commented on Assets/Script/Projectiles/ProjectileMovement.cs
> +    public bool destroySelfOnFirstCollision = false;
Changed.

2019-11-11 00:49 UTC, CCD729 commented on Assets/TestScript/MortarMovement.cs
> +    public bool destroySelfOnFirstCollision = false;
Changed. Also, all unnecessary public vars had been set to [SerializeField]

2019-11-11 01:02 UTC, kodomazer approved these changes
I don't really like stacking all the variable declarations, but we can deal with that later.

2019-11-11 11:00 UTC, merged